"""
train.py

Two-stage training pipeline:
1) Pre-train LSTM on historical features
2) Train PPO RL agent in custom StockTradingEnv using the trained LSTM predictor
"""

import os
import argparse
import logging

import pandas as pd
import numpy as np
import torch

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.callbacks import CheckpointCallback

# Project modules
from data_handler import DataHandler
from feature_engineer import FeatureEngineer
from lstm_state import train_lstm_model, LSTMPredictor
from trading_env import StockTradingEnv


# -------------------------
# Default configuration
# -------------------------
DEFAULT_TICKER = "AAPL"
START_DATE = "2015-01-01"
END_DATE = "2023-12-31"

# Data split boundaries
LSTM_TRAIN_END = "2020-12-31"
RL_TRAIN_START = "2021-01-01"
RL_TRAIN_END = "2022-12-31"

# LSTM hyperparameters
SEQ_LENGTH = 30
LSTM_HIDDEN_DIM = 64
LSTM_NUM_LAYERS = 2
LSTM_EPOCHS = 50
LSTM_MODEL_PATH = "models/lstm_state.pth"

# PPO hyperparameters
PPO_TIMESTEPS = 200_000
PPO_MODEL_PATH = "models/ppo_hybrid_trader.zip"
LOG_DIR = "logs/"

# Misc
RANDOM_SEED = 42
INITIAL_BALANCE = 10_000


# -------------------------
# Utilities
# -------------------------
def setup_logging():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[logging.StreamHandler()],
    )


def ensure_dirs(*paths):
    for p in paths:
        os.makedirs(os.path.dirname(p) or p, exist_ok=True)


def parse_args():
    parser = argparse.ArgumentParser(description="Train LSTM + PPO hybrid trading agent")
    parser.add_argument("--ticker", type=str, default=DEFAULT_TICKER)
    parser.add_argument("--start-date", type=str, default=START_DATE)
    parser.add_argument("--end-date", type=str, default=END_DATE)
    parser.add_argument("--lstm-epochs", type=int, default=LSTM_EPOCHS)
    parser.add_argument("--ppo-timesteps", type=int, default=PPO_TIMESTEPS)
    parser.add_argument("--use-cuda", action="store_true", help="Use GPU if available")
    return parser.parse_args()


def ensure_datetime_index(df: pd.DataFrame) -> pd.DataFrame:
    if "Date" in df.columns:
        df = df.copy()
        df["Date"] = pd.to_datetime(df["Date"])
        df = df.set_index("Date")

    # Ensure proper datetime index
    if not isinstance(df.index, pd.DatetimeIndex):
        try:
            df = df.copy()
            df.index = pd.to_datetime(df.index)
        except Exception as e:
            raise ValueError("DataFrame must have DatetimeIndex or convertible 'Date' column") from e

    return df.sort_index()


# -------------------------
# Main
# -------------------------
def main():
    setup_logging()
    args = parse_args()

    torch_device = "cuda" if (args.use_cuda and torch.cuda.is_available()) else "cpu"
    logging.info(f"Using device: {torch_device}")

    # Seeds
    np.random.seed(RANDOM_SEED)
    torch.manual_seed(RANDOM_SEED)

    # Make dirs
    ensure_dirs(LSTM_MODEL_PATH, PPO_MODEL_PATH, LOG_DIR)

    # -------------------------------
    # Load and process data
    # -------------------------------
    logging.info("Loading and processing data...")

    data_handler = DataHandler(
        symbols=[args.ticker],
        start_date=args.start_date,
        end_date=args.end_date,
    )

    df_raw = data_handler.download_data()
    if df_raw is None or df_raw.empty:
        raise RuntimeError("No data downloaded. Check ticker/date.")

    df_raw = ensure_datetime_index(df_raw)

    # Features
    fe = FeatureEngineer()
    features_df, feature_cols = fe.get_feature_df(df_raw)

    if features_df is None or features_df.empty:
        raise RuntimeError("No features generated by FeatureEngineer.")

    features_df = ensure_datetime_index(features_df)

    if "Close" not in features_df.columns:
        raise RuntimeError("Feature dataframe missing 'Close' column.")

    # -------------------------------
    # Stage 1: LSTM pre-training
    # -------------------------------
    logging.info("Stage 1: LSTM pre-training...")

    lstm_train_df = features_df.loc[:LSTM_TRAIN_END].copy()
    if lstm_train_df.empty:
        raise RuntimeError(f"No data for LSTM training before {LSTM_TRAIN_END}")

    logging.info(f"LSTM training samples: {len(lstm_train_df)}")

    train_lstm_model(
        train_df=lstm_train_df,
        feature_cols=feature_cols,
        target_col="Close",
        sequence_length=SEQ_LENGTH,
        hidden_dim=LSTM_HIDDEN_DIM,
        num_layers=LSTM_NUM_LAYERS,
        epochs=args.lstm_epochs,
        model_save_path=LSTM_MODEL_PATH,
    )

    # -------------------------------
    # Stage 2: RL Training (PPO)
    # -------------------------------
    logging.info("Stage 2: PPO RL training...")

    # Load predictor (not used directly in env yet)
    LSTMPredictor(
        model_path=LSTM_MODEL_PATH,
        input_dim=len(feature_cols),
        hidden_dim=LSTM_HIDDEN_DIM,
        num_layers=LSTM_NUM_LAYERS,
    )

    rl_train_df = features_df.loc[RL_TRAIN_START:RL_TRAIN_END].copy()
    if rl_train_df.empty:
        raise RuntimeError(f"No RL training data between {RL_TRAIN_START} and {RL_TRAIN_END}")

    logging.info(f"RL training samples: {len(rl_train_df)}")

    # -------- ENV FACTORY FOR SB3 --------
    def make_env():
        return StockTradingEnv(
            df=rl_train_df.copy().reset_index(drop=True),
            feature_cols=feature_cols,
            initial_balance=INITIAL_BALANCE,
        )

    vec_env = DummyVecEnv([make_env])

    # Policy: simple MLP for continuous Box observations
    policy = "MlpPolicy"

    # Define PPO model
    model = PPO(
        policy,
        vec_env,
        verbose=1,
        tensorboard_log=LOG_DIR,
        device=torch_device,
    )

    checkpoint_callback = CheckpointCallback(
        save_freq=max(args.ppo_timesteps // 10, 1000),
        save_path=LOG_DIR,
        name_prefix="ppo_checkpoint",
    )

    logging.info(f"Training PPO for {args.ppo_timesteps} timesteps...")
    model.learn(total_timesteps=args.ppo_timesteps, callback=checkpoint_callback)

    # Save final model
    model.save(PPO_MODEL_PATH)

    logging.info("Training finished successfully.")
    logging.info(f"LSTM saved to: {LSTM_MODEL_PATH}")
    logging.info(f"PPO saved to: {PPO_MODEL_PATH}")
    logging.info(f"Logs saved to: {LOG_DIR}")


if __name__ == "__main__":
    main()
